DROP TABLE IF EXISTS CITY;  
CREATE TABLE CITY (  
City_code INT AUTO_INCREMENT  PRIMARY KEY,  
city_name VARCHAR(50) NOT NULL,  
city_pincode INT(8) NOT NULL  
);

DROP TABLE IF EXISTS STUDENT;  
CREATE TABLE STUDENT (  
id INT AUTO_INCREMENT  PRIMARY KEY,  
name VARCHAR(50) NOT NULL,  
age INT(8) NOT NULL,  
email VARCHAR(50) NOT NULL
);